<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>pokecreator_api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PKHeX.Core" Version="26.5.5" />
  </ItemGroup>

</Project>
